 
name: Build Msi

on:
  push:
    branches:    
      - master
    tags: [ '*' ]

jobs:
  windows_build:
    name: Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: temurin
            
      - name: Build Msi
        uses: gradle/gradle-build-action@v2.4.0 
        with:
          arguments: "packageMsi --backtrace"
          
#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew
#       - name: Create Windows Distribution
#         run: ./gradlew packageMsi --info
